<a href="https://colab.research.google.com/github/Gerol-steiner/Knowledge/blob/main/20250731_NumPy%E3%81%A7NN%E5%AE%9F%E8%A3%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# ■ 入力→中間（２→３）

## 1. 「重み」の作成

In [3]:
# 2行3列の重み
np.random.seed(1)
W1 = np.random.randn(2,3) # ノード数「２→３」なので「２x３」行列にすればよい
W1

array([[ 1.62434536, -0.61175641, -0.52817175],
       [-1.07296862,  0.86540763, -2.3015387 ]])

## 2. 「バイアス」の作成

In [4]:
b1 = np.random.randn(3) # サンプル数に関わらず「3（OUT側のノード数）」
b1

array([ 1.74481176, -0.7612069 ,  0.3190391 ])

In [ ]:
b1.shape

(3,)

## 3. 「入力値」の作成

In [ ]:
# サンプル数：10、入力変数：2
x = np.random.randn(10,2)
x

array([[-0.24937038,  1.46210794],
       [-2.06014071, -0.3224172 ],
       [-0.38405435,  1.13376944],
       [-1.09989127, -0.17242821],
       [-0.87785842,  0.04221375],
       [ 0.58281521, -1.10061918],
       [ 1.14472371,  0.90159072],
       [ 0.50249434,  0.90085595],
       [-0.68372786, -0.12289023],
       [-0.93576943, -0.26788808]])

In [ ]:
x.shape

(10, 2)

In [ ]:
W1.shape

(2, 3)

In [ ]:
# 線形変換を行う
u1 = np.dot(x, W1) + b1    # np.dot() : 行列積
u1 # 10サンプル x [u1, u2, u3]

array([[-0.22904779,  0.65666639, -2.91434851],
       [-1.2556247 ,  0.22007508,  2.1492029 ],
       [-0.09552418,  0.45491354, -2.08752849],
       [ 0.14321854, -0.23756205,  1.29682079],
       [ 0.27357249, -0.18763928,  0.68554254],
       [ 3.8724348 , -2.07023208,  2.54433019],
       [ 2.63685986, -0.68125548, -2.36061756],
       [ 1.59444595, -0.28900342, -2.01971905],
       [ 0.76605894, -0.44928214,  0.96300145],
       [ 0.51223453, -0.42057634,  1.42984086]])

In [ ]:
u1.shape

(10, 3)

In [ ]:
# シグモイド関数を作る
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [ ]:
sigmoid(u1)

array([[0.44298709, 0.65851114, 0.05144881],
       [0.22172799, 0.55479778, 0.89559427],
       [0.4761371 , 0.61180683, 0.11031491],
       [0.53574356, 0.44088723, 0.78529944],
       [0.56796973, 0.45322733, 0.66497461],
       [0.97961649, 0.11202395, 0.92719169],
       [0.93319647, 0.33598115, 0.08622552],
       [0.8312407 , 0.42824786, 0.11714805],
       [0.68266775, 0.38953146, 0.72372234],
       [0.62533015, 0.39637885, 0.80687652]])

In [ ]:
sigmoid(u1).shape

(10, 3)

In [ ]:
def relu(x):
    return np.maximum(0,x)

In [ ]:
z1 = relu(u1)
z1 # 10サンプル x [z1, z2, z3]

array([[0.        , 0.65666639, 0.        ],
       [0.        , 0.22007508, 2.1492029 ],
       [0.        , 0.45491354, 0.        ],
       [0.14321854, 0.        , 1.29682079],
       [0.27357249, 0.        , 0.68554254],
       [3.8724348 , 0.        , 2.54433019],
       [2.63685986, 0.        , 0.        ],
       [1.59444595, 0.        , 0.        ],
       [0.76605894, 0.        , 0.96300145],
       [0.51223453, 0.        , 1.42984086]])

### 中間→出力（３→２）

In [ ]:
# 重み
W2 = np.random.randn(3,2) # 「重み」は「in (ノード数) ｘ out (ノード数)
W2

array([[ 0.53035547, -0.69166075],
       [-0.39675353, -0.6871727 ],
       [-0.84520564, -0.67124613]])

In [ ]:
b2 = np.random.randn(2) # OUT側のノード数
b2

array([-0.0126646 , -1.11731035])

In [ ]:
u2 = np.dot(z1, W2) + b2
u2

array([[-0.2731993 , -1.56855356],
       [-1.91649858, -2.71118407],
       [-0.19315315, -1.42991451],
       [-1.03278811, -2.08685493],
       [-0.44699836, -1.76669748],
       [-0.10937987, -5.50359331],
       [ 1.38580844, -2.94112282],
       [ 0.83295853, -2.22012603],
       [-0.42031531, -2.29357425],
       [-0.94950778, -2.43137801]])

In [ ]:
# ソフトマックス関数
def softmax(x):
    exp_x = np.exp(x-np.max(x))
    return exp_x/np.sum(exp_x)

In [ ]:
a = softmax(u2) # u2の全ての要素を足すと１となってしまっている
a

array([[0.06273367, 0.01717653],
       [0.012129  , 0.00547895],
       [0.06796171, 0.01973084],
       [0.0293505 , 0.01022916],
       [0.0527255 , 0.01408908],
       [0.07390036, 0.00033571],
       [0.32960863, 0.00435348],
       [0.18962645, 0.00895285],
       [0.05415131, 0.00831884],
       [0.03189948, 0.00724796]])

softmax(u2[0]) # u2の１行目の2要素のみにsoftmaxを適用

In [ ]:
np.sum(a)

np.float64(1.0000000000000002)

In [ ]:
y = softmax(u2[0]) # u2の１行目の2要素のみにsoftmaxを適用
y

array([0.78505207, 0.21494793])

In [ ]:
np.argmax(y)

np.int64(0)

In [ ]:
def softmax(x):
    if x.ndim == 2:
        x = x-np.max(x, axis=1, keepdims=True)
        x = np.exp(x)
        x /= np.sum(x, axis=1, keepdims=True)
    elif x.ndim == 1:
        x = x-np.max(x)
        x = np.exp(x)/np.sum(np.exp(x))

    return x

In [ ]:
b = softmax(u2) # u2の全ての要素を足すと１となってしまっている
b

array([[0.78505207, 0.21494793],
       [0.68883651, 0.31116349],
       [0.77499978, 0.22500022],
       [0.74155508, 0.25844492],
       [0.78913164, 0.21086836],
       [0.99547775, 0.00452225],
       [0.98696416, 0.01303584],
       [0.95491551, 0.04508449],
       [0.86683491, 0.13316509],
       [0.8148549 , 0.1851451 ]])